# Generated by Django 5.2.9 on 2025-12-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main product image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.productimage'),
        ),
    ]
