# Generated by Django 5.2.9 on 2025-12-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productdescription_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='product',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_description', to='store.product'),
            preserve_default=False,
        ),
    ]
