# Generated by Django 5.2.9 on 2025-12-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productdescription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='store.product'),
        ),
    ]
