# Generated by Django 5.2.9 on 2025-12-30 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_category_description_remove_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Information key (e.g., Material, Dimensions)', max_length=255)),
                ('value', models.CharField(help_text='Information value (e.g., Cotton, 10x5x2 inches)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Additional Info',
                'verbose_name_plural': 'Product Additional Info',
                'db_table': 'product_additional_info',
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_type', models.CharField(help_text='Type of variant (e.g., Size, Color)', max_length=100)),
                ('variant_value', models.CharField(help_text='Value of the variant (e.g., Red, Large)', max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price for this variant', max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'unique_together': {('product', 'variant_type', 'variant_value')},
            },
        ),
    ]
