# Generated by Django 5.2.9 on 2025-12-31 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productadditionalinfo_productvariants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadditionalinfo',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='store.productvariants'),
        ),
        migrations.AlterField(
            model_name='productadditionalinfo',
            name='value',
            field=models.TextField(help_text='Information value (e.g., Cotton, 10x5x2 inches)', max_length=255),
        ),
    ]
