# Generated by Django 5.2.9 on 2025-12-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productadditionalinfo_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadditionalinfo',
            name='value',
            field=models.TextField(help_text='Information value (e.g., Cotton, 10x5x2 inches)', max_length=2200),
        ),
    ]
