# Generated by Django 5.2.9 on 2026-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_slider',
            field=models.BooleanField(default=False, help_text='Display in homepage slider'),
        ),
    ]
