# Generated by Django 5.2.9 on 2026-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_is_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productadditionalinfo',
            options={'ordering': ['order', 'key', 'variant_name'], 'verbose_name': 'Product Additional Info', 'verbose_name_plural': 'Product Additional Info'},
        ),
        migrations.RemoveField(
            model_name='productadditionalinfo',
            name='variant',
        ),
        migrations.AddField(
            model_name='productadditionalinfo',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order of the specification row'),
        ),
        migrations.AddField(
            model_name='productadditionalinfo',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Variant/Model name (e.g., iPhone 6s, iPhone 6s Plus)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productadditionalinfo',
            name='key',
            field=models.CharField(help_text='Information key (e.g., Capacity, Display, Chip)', max_length=255),
        ),
        migrations.AlterField(
            model_name='productadditionalinfo',
            name='value',
            field=models.TextField(help_text='Information value (e.g., 16GB/64GB/128GB, Retina Display)', max_length=2200),
        ),
    ]
